### ISSUE TITLE
0.13.1 doesn't work in IE and Edge

### ISSUE THREAD

**Issue by BenRJDictus** [thewca/tnoodle#337] opened 2018-01-31 08:53 UTC
I tested the new TNoodle and it only works in Firefox (58)
In IE and Edge it just flashes the two buttons and then goes blank.

I have fully updated Windows 10 x64 with Java 8.161

**Comment by jfly** [comment] 2018-01-31 16:55
I believe this is a duplicate of #335. Thanks for the report!

**Closed by jfly** 2018-01-31 16:55 UTC
