### ISSUE TITLE
Investigate generic scrambler

### ISSUE THREAD

**Issue by jfly** [thewca/tnoodle#123] opened 2013-09-29 00:03 UTC
5x5, 6x6, and 7x7 take embarrassingly long to scramble. There must be some way of improving this without writing puzzle specific logic.

**Comment by suushiemaniac** [comment] 2020-01-04 11:37
This feels like a duplicate of #194 and I'd like to close this issue. T-3 days to object :)

**Closed** 2020-01-17 10:22 UTC
