### ISSUE TITLE
support Dart

### ISSUE THREAD

**Issue by LXD312569496** [thewca/tnoodle#485] opened 2020-01-17 10:04 UTC
Can this project support to use in dart or Flutter? Do you want to do this?

**Comment by suushiemaniac** [comment] 2020-01-17 10:08
Closed as duplicate of #449.
Please refer to my instructions on that post for details, and feel free to open another issue if a specific piece of code is not working in Flutter as expected.

**Closed by suushiemaniac** 2020-01-17 10:08 UTC
