### ISSUE TITLE
Scramble Passwords Are "Crackable" Too Easily

### ISSUE THREAD

**Issue by Carter-Thomas** [thewca/tnoodle#838] opened 2023-07-03 21:36 UTC
Is your feature request related to a problem? Please describe.
The 32 character 8 length passwords used in tnoodle can be cracked in three and a half hours on average with an RTX 3070. With an RTX 4090, and a little bit of luck, these can be cracked in close to an hour on average.

Describe the solution you'd like
Either increase the password length to 10 (makes cracking take 1000x as long), only release scramble sheets when a round is scheduled on the WCA, or prevent displaying scrambles on non-delegate devices (first option is probably the easiest).

Additional context [OPTIONAL]
I was able to crack a tnoodle password using hashcat in about two hours with the current password generation. The reason for this change is that scrambles (without passwords) are typically emailed to whoever's device is being used to display scrambles. If a malicious user wanted to gain access to a scramble set later in the day, they could easily do so, even without an accomplice. 

![Screenshot (451)](https://github.com/thewca/tnoodle/assets/77213551/1df145d9-d7d1-4854-bc1d-4aabf7094965)

Here's a screenshot with the finished hashcat run

**Comment by coder13** [comment] 2023-07-04 00:25
Who's going to do this though? The passwords are more of a formality to make sure we're opening the right scramble set and so that scramblers don't look ahead.

**Comment by Carter-Thomas** [comment] 2023-07-04 00:32
I wrote what case this could be possible, and that's when an organizer is emailed a display set. At competitions I have organized, it is quite common to use an organizer's device to display scrambles. If the owner of said device wanted to cheat, they could simply run the program and wait a few hours. I don't really think it's that much of an inconvenience either way to add two digits to simply prevent this though.

**Comment by gregorbg** [comment] 2023-07-10 20:57
This is an age-old argument that exists almost as long as TNoodle.

Essentially, it's a five minute and two lines of code change to add _much_ stronger encryption to the ZIPs produced by TNoodle. The problem is that this relies on encryption algorithms that are not supported by most native archiving tools (Windows, Mac). So by upgrading password security (which from a TNoodle maintainer standpoint is easy as a breeze!) would effectively mean forcing all our Delegates (even the ones who are not so adept at using digital programs) to download third party archiving software.

A consensus around this problem has not been reached yet. Closing this issue as a duplicate of https://github.com/thewca/tnoodle/issues/198

**Closed by gregorbg** 2023-07-10 20:57 UTC
